version: '3.7'

services:
  postgres:
    image: postgis/postgis:13-3.1
    container_name: postgres
    environment:
      POSTGRES_DB: geodata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 3

  load_data:
    image: python:3.9-slim
    container_name: load_data
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "pip install -r requirements.txt && python load_geojson.py"

volumes:
  pgdata:
    driver: local
